In [100]:
import os, sys, datetime
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix

In [101]:
df = pd.read_csv('churn.csv')

In [102]:
df['Churn']= df['Churn'].apply(lambda x : 1 if x=='Yes' else 0)

df['TotalCharges']=pd.to_numeric(df['TotalCharges'])
df = df.dropna()

In [4]:
df

customerID  gender  SeniorCitizen Partner Dependents  tenure  \
0     7590-VHVEG  Female              0     Yes         No       1   
1     5575-GNVDE    Male              0      No         No      34   
2     3668-QPYBK    Male              0      No         No       2   
3     7795-CFOCW    Male              0      No         No      45   
4     9237-HQITU  Female              0      No         No       2   
...          ...     ...            ...     ...        ...     ...   
7038  6840-RESVB    Male              0     Yes        Yes      24   
7039  2234-XADUH  Female              0     Yes        Yes      72   
7040  4801-JZAZL  Female              0     Yes        Yes      11   
7041  8361-LTMKD    Male              1     Yes         No       4   
7042  3186-AJIEK    Male              0      No         No      66   

     PhoneService     MultipleLines InternetService OnlineSecurity  ...  \
0              No  No phone service             DSL             No  ...   
1             Yes                No             DSL            Yes  ...   
2             Yes                No             DSL            Yes  ...   
3              No  No phone service             DSL            Yes  ...   
4             Yes                No     Fiber optic             No  ...   
...           ...               ...             ...            ...  ...   
7038          Yes               Yes             DSL            Yes  ...   
7039          Yes               Yes     Fiber optic             No  ...   
7040           No  No phone service             DSL            Yes  ...   
7041          Yes               Yes     Fiber optic             No  ...   
7042          Yes                No     Fiber optic            Yes  ...   

     DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
0                  No          No          No              No  Month-to-month   
1                 Yes          No          No              No        One year   
2                  No          No          No              No  Month-to-month   
3                 Yes         Yes          No              No        One year   
4                  No          No          No              No  Month-to-month   
...               ...         ...         ...             ...             ...   
7038              Yes         Yes         Yes             Yes        One year   
7039              Yes          No         Yes             Yes        One year   
7040               No          No          No              No  Month-to-month   
7041               No          No          No              No  Month-to-month   
7042              Yes         Yes         Yes             Yes        Two year   

     PaperlessBilling              PaymentMethod MonthlyCharges  TotalCharges  \
0                 Yes           Electronic check          29.85         29.85   
1                  No               Mailed check          56.95       1889.50   
2                 Yes               Mailed check          53.85        108.15   
3                  No  Bank transfer (automatic)          42.30       1840.75   
4                 Yes           Electronic check          70.70        151.65   
...               ...                        ...            ...           ...   
7038              Yes               Mailed check          84.80       1990.50   
7039              Yes    Credit card (automatic)         103.20       7362.90   
7040              Yes           Electronic check          29.60        346.45   
7041              Yes               Mailed check          74.40        306.60   
7042              Yes  Bank transfer (automatic)         105.65       6844.50   

      Churn  
0         0  
1         0  
2         1  
3         0  
4         1  
...     ...  
7038      0  
7039      0  
7040      0  
7041      1  
7042      0  

[7032 rows x 21 columns]

In [103]:
X = df.drop(columns=["customerID","Churn"])

y = df["Churn"]


X.shape, y.shape

((7032, 19), (7032,))

In [104]:
# Séparation train/val/test (80/20 puis 20% de train pour val)
X_train_0, X_test, y_train_0, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# On prend 20% de X_train pour validation
X_train, X_val, y_train, y_val = train_test_split(
    X_train_0, y_train_0, test_size=0.2, random_state=42, stratify=y_train_0
)
X_train.shape, X_test.shape, X_val.shape, X_test.shape, y_val.shape, y_test.shape

((4500, 19), (1407, 19), (1125, 19), (1407, 19), (1125,), (1407,))

In [105]:
df['TotalCharges']=pd.to_numeric(df['TotalCharges'])

In [106]:
import pandas as pd
import numpy as np

from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet
from sklearn.preprocessing import OneHotEncoder, LabelBinarizer, MinMaxScaler, StandardScaler, PolynomialFeatures, Binarizer, KBinsDiscretizer, OrdinalEncoder
from sklearn.model_selection import train_test_split, cross_val_score, learning_curve, GridSearchCV
from sklearn.pipeline import make_pipeline
from sklearn.compose import make_column_transformer, make_column_selector
from sklearn.base import BaseEstimator, TransformerMixin
import pandas as pd
import numpy as np
from sklearn.model_selection import cross_validate, GridSearchCV, train_test_split
from sklearn.pipeline import make_pipeline, Pipeline
from sklearn.compose import ColumnTransformer, TransformedTargetRegressor
from sklearn.preprocessing import PolynomialFeatures, OrdinalEncoder, OneHotEncoder, StandardScaler, RobustScaler, LabelEncoder
from sklearn.base import BaseEstimator, TransformerMixin
import matplotlib.pyplot as plt
from sklearn.metrics import roc_auc_score,make_scorer, accuracy_score, f1_score, recall_score, classification_report
import seaborn as sns
from sklearn.model_selection import GridSearchCV,KFold
import warnings


features_of_interest = [
    'gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
    'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
    'PaymentMethod', 'MonthlyCharges', 'TotalCharges'
]

numerical_column = ['tenure','MonthlyCharges','TotalCharges']


target_name = 'Churn'

categorical_column = [
    'gender','SeniorCitizen','Partner','Dependents','PhoneService','MultipleLines','InternetService','OnlineSecurity','OnlineBackup','DeviceProtection','TechSupport',
    'StreamingTV','StreamingMovies','Contract','PaperlessBilling'
]

one_hot_column = ['PaymentMethod']


In [107]:
preprocessor = ColumnTransformer(
    [('categorical', OrdinalEncoder(), categorical_column),
     ('one_hot', OneHotEncoder(handle_unknown='ignore'), one_hot_column),
     ('numeric', StandardScaler(), numerical_column)
    ],
    remainder='passthrough'
)

In [108]:
from sklearn.pipeline import make_pipeline
from sklearn.linear_model import LogisticRegression

logistic_regression_model = make_pipeline(preprocessor,LogisticRegression())
logistic_regression_model.fit(X_train_0, y_train_0)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('categorical',
                                                  OrdinalEncoder(),
                                                  ['gender', 'SeniorCitizen',
                                                   'Partner', 'Dependents',
                                                   'PhoneService',
                                                   'MultipleLines',
                                                   'InternetService',
                                                   'OnlineSecurity',
                                                   'OnlineBackup',
                                                   'DeviceProtection',
                                                   'TechSupport', 'StreamingTV',
                                                   'StreamingMovies',
                                                   'Contract',
                                                   'PaperlessBilling']),
                                                 ('one_hot',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['PaymentMethod']),
                                                 ('numeric', StandardScaler(),
                                                  ['tenure', 'MonthlyCharges',
                                                   'TotalCharges'])])),
                ('logisticregression', LogisticRegression())])

In [110]:
print('accuracy', logistic_regression_model.score(X_test,y_test))

accuracy 0.8017057569296375


In [115]:
from sklearn.metrics import recall_score, f1_score

predictions = logistic_regression_model.predict(X_test)
print(recall_score(y_test, predictions))
print(f1_score(y_test, predictions))


0.56951871657754
0.6042553191489362


In [63]:
# Normalisation des features numériques
X_train = preprocessor.fit_transform(X_train)
X_val  = preprocessor.transform(X_val)
X_test  = preprocessor.transform(X_test)
X_train[:5], X_val[:5], X_test[:5]

(array([[ 1.        ,  0.        ,  0.        ,  0.        ,  1.        ,
          0.        ,  0.        ,  2.        ,  0.        ,  0.        ,
          2.        ,  0.        ,  0.        ,  0.        ,  1.        ,
          0.        ,  0.        ,  0.        ,  1.        , -1.24544953,
         -0.35110108, -0.97553063],
        [ 1.        ,  0.        ,  0.        ,  0.        ,  1.        ,
          0.        ,  2.        ,  1.        ,  1.        ,  1.        ,
          1.        ,  1.        ,  1.        ,  1.        ,  0.        ,
          1.        ,  0.        ,  0.        ,  0.        ,  0.62934087,
         -1.50480072, -0.56967839],
        [ 0.        ,  0.        ,  0.        ,  0.        ,  1.        ,
          0.        ,  0.        ,  0.        ,  2.        ,  0.        ,
          0.        ,  2.        ,  0.        ,  1.        ,  1.        ,
          0.        ,  1.        ,  0.        ,  0.        ,  0.26253406,
         -0.21232272, -0.02984005],
    

In [12]:
for i in range(len(X_train)):
    for j in range(len(X_train[i])):
        if np.isnan(X_train[i][j]):
            print(i, j)

In [13]:

np.isnan(X_train)


array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [64]:
num_classes = len(np.unique(y))
np.unique(y), num_classes

(array([0, 1]), 2)

In [65]:
import tensorflow as tf

y_train_cat = tf.keras.utils.to_categorical(y_train, num_classes)
y_val_cat = tf.keras.utils.to_categorical(y_val, num_classes)
y_test_cat  = tf.keras.utils.to_categorical(y_test,  num_classes)
y_train_cat[:5], y_val_cat[:5], y_test_cat[:5]

(array([[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [0., 1.]]),
 array([[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]),
 array([[1., 0.],
        [1., 0.],
        [1., 0.],
        [0., 1.],
        [1., 0.]]))

In [66]:
def build_model():
    # Réseau avec 2 couches cachées de 64 neurones chacune
    # et une couche de sortie avec activation softmax pour classification
    model = tf.keras.Sequential([
        tf.keras.layers.Input(shape=(X_train.shape[1],)),
        tf.keras.layers.Dense(64, activation='relu'),
        tf.keras.layers.Dense(64, activation='relu'),
        tf.keras.layers.Dense(num_classes, activation='softmax')
    ])

    # Définition de la fonction de perte, de l'optimiseur et des métriques
    model.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=0.01), #fonction coût avec fonction Adam, optimisation des poids
        loss='categorical_crossentropy', # fonction à minimiser
        metrics=['accuracy', 'recall', 'f1_score', tf.keras.metrics.AUC()] # évlaluation de la qualité
    )

    model.summary()

    return model

In [79]:
early_stop= tf.keras.callbacks.EarlyStopping(
    monitor='val_recall',    # surveille la perte de validation
    patience=10,            # tolère 3 époques sans amélioration
    restore_best_weights=True
)

In [81]:
checkpoint_path = "churn_deeplearning/churn_best.keras"
os.makedirs(os.path.dirname(checkpoint_path), exist_ok=True)
model_ckpt = tf.keras.callbacks.ModelCheckpoint(
    filepath=checkpoint_path,
    monitor='val_recall',  # sauvegarde le modèle qui maximise l’accuracy de validation
    save_best_only=True,
    verbose=1
)

In [67]:
model = build_model()

Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_21 (Dense)                │ (None, 64)             │         1,472 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_22 (Dense)                │ (None, 64)             │         4,160 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_23 (Dense)                │ (None, 2)              │           130 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 5,762 (22.51 KB)

 Trainable params: 5,762 (22.51 KB)

 Non-trainable params: 0 (0.00 B)

In [82]:
history = model.fit(
    X_train, y_train_cat,
    validation_data=(X_val, y_val_cat),
    epochs=40,
    batch_size=64,
    verbose=1,
    callbacks=[early_stop, model_ckpt]
)

Epoch 1/40
48/71 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8983 - auc_1: 0.9759 - f1_score: 0.8668 - loss: 0.1885 - recall: 0.8983
Epoch 1: val_recall improved from inf to 0.76356, saving model to churn_deeplearning/churn_best.keras
71/71 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8969 - auc_1: 0.9754 - f1_score: 0.8660 - loss: 0.1906 - recall: 0.8969 - val_accuracy: 0.7636 - val_auc_1: 0.8144 - val_f1_score: 0.7056 - val_loss: 1.8541 - val_recall: 0.7636
Epoch 2/40
51/71 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8994 - auc_1: 0.9760 - f1_score: 0.8729 - loss: 0.1887 - recall: 0.8994
Epoch 2: val_recall improved from 0.76356 to 0.75022, saving model to churn_deeplearning/churn_best.keras
71/71 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8987 - auc_1: 0.9754 - f1_score: 0.8718 - loss: 0.1915 - recall: 0.8987 - val_accuracy: 0.7502 - val_auc_1: 0.8102 - val_f1_score: 0.6963 - val_loss: 1.7506 - val_recall: 0.7502
Epoch 3/40
53/71 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accura

In [ ]:
y_pred_probs = model.predict(X_test)
y_pred = np.argmax(y_pred_probs, axis=1)
print("\nClassification Report :")
print(classification_report(y_test, y_pred))

44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 909us/step

Classification Report :
              precision    recall  f1-score   support

           0       0.82      0.89      0.85      1033
           1       0.60      0.47      0.53       374

    accuracy                           0.78      1407
   macro avg       0.71      0.68      0.69      1407
weighted avg       0.76      0.78      0.77      1407



In [29]:
mylist = sorted(history.history['accuracy'])
mylist

[0.8902222514152527,
 0.8913333415985107,
 0.891777753829956,
 0.8946666717529297,
 0.8964444398880005,
 0.8973333239555359,
 0.8973333239555359,
 0.8973333239555359,
 0.8975555300712585,
 0.8980000019073486,
 0.8982222080230713,
 0.8984444737434387,
 0.8986666798591614,
 0.8997777700424194,
 0.9002222418785095,
 0.9006666541099548,
 0.9006666541099548,
 0.9011111259460449,
 0.9015555381774902,
 0.9015555381774902,
 0.9017778038978577,
 0.9020000100135803,
 0.9024444222450256,
 0.9024444222450256,
 0.9026666879653931,
 0.9026666879653931,
 0.9026666879653931,
 0.9028888940811157,
 0.9028888940811157,
 0.9028888940811157,
 0.9031111001968384,
 0.9031111001968384,
 0.903333306312561,
 0.9035555720329285,
 0.9037777781486511,
 0.9044444561004639,
 0.9046666622161865,
 0.9046666622161865,
 0.9048888683319092,
 0.9048888683319092,
 0.9051111340522766,
 0.9053333401679993,
 0.9055555462837219,
 0.9055555462837219,
 0.9057777523994446,
 0.906000018119812,
 0.906000018119812,
 0.90688890218734